/*
UBill API

UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.

API version: 2.1.7
Contact: info@ubill.ge
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ubill

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateBrandNameResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBrandNameResponse{}

// CreateBrandNameResponse struct for CreateBrandNameResponse
type CreateBrandNameResponse struct {
	// Response status code
	StatusID int64 `json:"statusID"`
	// Human-readable response message
	Message *string `json:"message,omitempty"`
	// Brand identifier
	BrandID *int64 `json:"brandID,omitempty"`
}

type _CreateBrandNameResponse CreateBrandNameResponse

// NewCreateBrandNameResponse instantiates a new CreateBrandNameResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBrandNameResponse(statusID int64) *CreateBrandNameResponse {
	this := CreateBrandNameResponse{}
	this.StatusID = statusID
	return &this
}

// NewCreateBrandNameResponseWithDefaults instantiates a new CreateBrandNameResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBrandNameResponseWithDefaults() *CreateBrandNameResponse {
	this := CreateBrandNameResponse{}
	return &this
}

// GetStatusID returns the StatusID field value
func (o *CreateBrandNameResponse) GetStatusID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StatusID
}

// GetStatusIDOk returns a tuple with the StatusID field value
// and a boolean to check if the value has been set.
func (o *CreateBrandNameResponse) GetStatusIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusID, true
}

// SetStatusID sets field value
func (o *CreateBrandNameResponse) SetStatusID(v int64) {
	o.StatusID = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateBrandNameResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBrandNameResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateBrandNameResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateBrandNameResponse) SetMessage(v string) {
	o.Message = &v
}

// GetBrandID returns the BrandID field value if set, zero value otherwise.
func (o *CreateBrandNameResponse) GetBrandID() int64 {
	if o == nil || IsNil(o.BrandID) {
		var ret int64
		return ret
	}
	return *o.BrandID
}

// GetBrandIDOk returns a tuple with the BrandID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBrandNameResponse) GetBrandIDOk() (*int64, bool) {
	if o == nil || IsNil(o.BrandID) {
		return nil, false
	}
	return o.BrandID, true
}

// HasBrandID returns a boolean if a field has been set.
func (o *CreateBrandNameResponse) HasBrandID() bool {
	if o != nil && !IsNil(o.BrandID) {
		return true
	}

	return false
}

// SetBrandID gets a reference to the given int64 and assigns it to the BrandID field.
func (o *CreateBrandNameResponse) SetBrandID(v int64) {
	o.BrandID = &v
}

func (o CreateBrandNameResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBrandNameResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["statusID"] = o.StatusID
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.BrandID) {
		toSerialize["brandID"] = o.BrandID
	}
	return toSerialize, nil
}

func (o *CreateBrandNameResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"statusID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBrandNameResponse := _CreateBrandNameResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBrandNameResponse)

	if err != nil {
		return err
	}

	*o = CreateBrandNameResponse(varCreateBrandNameResponse)

	return err
}

type NullableCreateBrandNameResponse struct {
	value *CreateBrandNameResponse
	isSet bool
}

func (v NullableCreateBrandNameResponse) Get() *CreateBrandNameResponse {
	return v.value
}

func (v *NullableCreateBrandNameResponse) Set(val *CreateBrandNameResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBrandNameResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBrandNameResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBrandNameResponse(val *CreateBrandNameResponse) *NullableCreateBrandNameResponse {
	return &NullableCreateBrandNameResponse{value: val, isSet: true}
}

func (v NullableCreateBrandNameResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBrandNameResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
