/*
UBill API

UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.

API version: 2.1.7
Contact: info@ubill.ge
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ubill

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SendSMSResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendSMSResponse{}

// SendSMSResponse struct for SendSMSResponse
type SendSMSResponse struct {
	// Response status code
	StatusID int64 `json:"statusID"`
	// Human-readable response message
	Message *string `json:"message,omitempty"`
	SmsID   *string `json:"smsID,omitempty"`
}

type _SendSMSResponse SendSMSResponse

// NewSendSMSResponse instantiates a new SendSMSResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendSMSResponse(statusID int64) *SendSMSResponse {
	this := SendSMSResponse{}
	this.StatusID = statusID
	return &this
}

// NewSendSMSResponseWithDefaults instantiates a new SendSMSResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendSMSResponseWithDefaults() *SendSMSResponse {
	this := SendSMSResponse{}
	return &this
}

// GetStatusID returns the StatusID field value
func (o *SendSMSResponse) GetStatusID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StatusID
}

// GetStatusIDOk returns a tuple with the StatusID field value
// and a boolean to check if the value has been set.
func (o *SendSMSResponse) GetStatusIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusID, true
}

// SetStatusID sets field value
func (o *SendSMSResponse) SetStatusID(v int64) {
	o.StatusID = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SendSMSResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendSMSResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SendSMSResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SendSMSResponse) SetMessage(v string) {
	o.Message = &v
}

// GetSmsID returns the SmsID field value if set, zero value otherwise.
func (o *SendSMSResponse) GetSmsID() string {
	if o == nil || IsNil(o.SmsID) {
		var ret string
		return ret
	}
	return *o.SmsID
}

// GetSmsIDOk returns a tuple with the SmsID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendSMSResponse) GetSmsIDOk() (*string, bool) {
	if o == nil || IsNil(o.SmsID) {
		return nil, false
	}
	return o.SmsID, true
}

// HasSmsID returns a boolean if a field has been set.
func (o *SendSMSResponse) HasSmsID() bool {
	if o != nil && !IsNil(o.SmsID) {
		return true
	}

	return false
}

// SetSmsID gets a reference to the given string and assigns it to the SmsID field.
func (o *SendSMSResponse) SetSmsID(v string) {
	o.SmsID = &v
}

func (o SendSMSResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendSMSResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["statusID"] = o.StatusID
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.SmsID) {
		toSerialize["smsID"] = o.SmsID
	}
	return toSerialize, nil
}

func (o *SendSMSResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"statusID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendSMSResponse := _SendSMSResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendSMSResponse)

	if err != nil {
		return err
	}

	*o = SendSMSResponse(varSendSMSResponse)

	return err
}

type NullableSendSMSResponse struct {
	value *SendSMSResponse
	isSet bool
}

func (v NullableSendSMSResponse) Get() *SendSMSResponse {
	return v.value
}

func (v *NullableSendSMSResponse) Set(val *SendSMSResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSendSMSResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSendSMSResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendSMSResponse(val *SendSMSResponse) *NullableSendSMSResponse {
	return &NullableSendSMSResponse{value: val, isSet: true}
}

func (v NullableSendSMSResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendSMSResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
